name: GodelScript Build

on:
  push:
    paths:
      - godel-script/**
  pull_request:
    branches: [ main ]
    paths:
      - godel-script/**
  workflow_dispatch:

jobs:
  mac-aarch64-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Update Git Env
      run: |
        git config --global user.name "$(git log -n 1 --pretty=format:%an)"
        git config --global user.email "$(git log -n 1 --pretty=format:%ae)"
    - name: Build
      run: |
        cd godel-script
        cd godel-backend/souffle
        git am ../0001-init-self-used-souffle-from-public-souffle.patch
        cd ../..
        mkdir build
        cd build
        cmake ..
        make -j6
    - name: Test
      run: |
        cd godel-script
        ./build/godel
        ./build/godel --version
        ./build/godel -h --color-off

  linux-x86_64-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Update Git Env
      run: |
        git config --global user.name "$(git log -n 1 --pretty=format:%an)"
        git config --global user.email "$(git log -n 1 --pretty=format:%ae)"
    - name: Install Package
      run: |
        sudo apt-get install sqlite3 libsqlite3-dev
    - name: Build
      run: |
        cd godel-script
        cd godel-backend/souffle
        git am ../0001-init-self-used-souffle-from-public-souffle.patch
        cd ../..
        mkdir build
        cd build
        cmake ..
        make -j6
    - name: Test
      run: |
        cd godel-script
        ./build/godel
        ./build/godel --version
        ./build/godel -h --color-off